---
driver:
  name: docker
  use_sudo: false
  customize:
    memory 1048

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: doc
  sudo_command: '. /etc/profile;'

platforms:
  - name: ubuntu-14.04
    driver_config:
     instance_name: sickle-ubuntu14.04

suites:
  - name: default
    run_list:
      - recipe[sickle::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
