sudo: required
dist: trusty
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
install: echo "skip bundle install"
branches:
  only:
  - master
services: docker
env:
  global:
  - RUBYOPT="-W0"
  - secure: aRQExXeM42pO6LXdE8+JhDFD/bdCVY1WDxRKaclpF+m9icf2ui5TRY8yJSrQrrx0BMGntW9MJyUXJAfvd3s8fkdEGjLlyOBk04XGV5J66tR4vy3dd8CnrdHmp8oCHEQSx3MgLUXQqapcG+a/9lGq5Wb1gHwtO6rEOU1VOTJNh4ohanfnYH184zXyPYV39U0xrzDNO1hgA6EmebMIBBLnbCSFqoLvYTPWN0JNwwHHgpIfQSIe4bCJ143SNUjNHazN443ht9qoQ6AMCwJkqSwq28hf3erL3uqy+LdiFKvXPxiS/Jd23Pxp2h2iSYoneZkgte6GUuuYT1Wi+BveUaW453WH+RQP6+wlsFzz+hlYd2H9Gk/vdnrMbzaVhd9YvlkOflN9WqKhb8NPFkF4eRZ51Au7S90proh7B8He+oM4O4eEmkA/BYpLNO+s4DSNQecmFNOZa7zcFJWcNnD4sOu2DDibRzX3281TJ+xr9nSwF9Yg5MgUcINLYZgMeyYcaa+ed3XLiFVLbEtzHaHWgE2UK9V7PvCeGHL9JrNrfSdEbXOo7uxRmE3TVLdAIokxHTbQ5K85wb9G8FhkZ6N1dL7yHMRamaQRQc1PHtBGeI0BntY/rylkEV7Uw6TpIXhG6dNVY7RdhBvIDhWF68LOFnoalVX6xwizXncKdtSVQSU01R0=
  matrix:
  - CHEF_VERSION=current INSTANCE=default-ubuntu-1404
before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables
  -N DOCKER )
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- chef gem install kitchen-docker
- "/opt/chefdk/bin/chef exec rake tests"
script:
- KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
notifications:
  slack:
    on_success: change
    on_failure: change
    secure: Zis5WtjZwsq/X92aQEz/bz5Pf3u95oQUrI2wNapkK23TxpePciwfLbnr2ontO5TgqOrsPl3+aJwIAS78QC7Px0cTHmodu9UGEC1eQcvI+lNOqKK2sLUYnTvw6vuKtQM0YM5fKgrtHXkzfC3KFAjPHYNd76rx6SJE+dOlbqBIP3opT+WZTX6JqfgVIAjGzFpi+WcIytnXNlvgbZFzGs3Rqg/mKgvDv93AwZVH97V8x3u5sOuJtSxz5hDKZ9tXSQyJjc8w3V5dj4RytMvCleCBo6sEHah7mxScc4AgBaU5h2gtEszm+7qfl0TczyIpLFs2GCITFtwDic0gOuEOPKVVrPWbRgdd9Vyn4mugwjuHkF9LEsnaEbYWe2G3619LDvwzNjrQz4Z70M3H8a9JYzmba/mmBzV6/bfsFSzzEA8tTM9KuAxAjZb6VMmuY2qbYsN0Ev/9I67YEY6ISkFo7JGZdVBvQ9CchHrhXbZTnKaMvH2ZmoIM7exlZ1Pe4CVk8iCAcQTSWCODf3fOzlRC+YaqEohlG440sYiOp8oglYqjUAaYMUHZz/RdSO36P0MNNr0VjDZhGYa3ZWgZygHkt2gvGlj3J+EA8C3Z+HH2zwuO8Um732yGlo4btNlVKFTf3hqv9ypeo9XCmWvG26PcnsKNDhlttyF3uvE5QNXLzNhccnE=
  email:
    on_success: change
    on_failure: change
after_success:
  - chmod +x trigger_dependent_build.sh
  - "./trigger_dependent_build.sh EagleGenomics-cookbooks sickle_runnable private $TRAVIS_ACCESS_TOKEN"
